### ISSUE TITLE
Subtitles Addon

### ISSUE THREAD

**Issue by adfcorreia** [shivasiddharth/Stremio-RaspberryPi#1]
After installing the software on rpi4, the subtitles add-on does not work. The following message is displayed: "Error loading subtitles, no addon supplies for this method/argument"

**Comment by atomms** [comment]
try changing to last stremio client:
http://app.strem.io/shell-v4.4/#/
in your /home/${USER}/Stremio-RaspberryPi/src/client-launcher.sh

**Comment by atomms** [comment]
by the way i still have problems with a slow performance -stremio client freezes again and again- until i open the stream with a different client such as omxplayer, but this omxplayer does not load subtitles as the default client does

stuck in the middle of this :/

**Comment by shivasiddharth** [comment]
Can you see if VLC works ? We have circumvented few packages to get Stremio running. So obviously you will not have the performance of the desktop version.

**Comment by atomms** [comment]
VLC does not start when i launch it from within server.js as with default options:

title: "VLC",
            args: ['--no-video-title-show'],
            subArg: '--sub-file=',
            timeArg: '--start-time=',
            playArg: '',
            darwin: {
                path: ["/Applications/VLC.app/Contents/MacOS/VLC"]
            },
            linux: {
                path: ['/usr/bin/vlc', '/usr/local/bin/vlc']
            },

VLC is working though from Desktop...

do you think it is about wrong vlc arguments?

**Comment by eldroan** [comment]
Having the same issues, have you got it to work?

**Comment by atomms** [comment]
not really, still needing VLC to play but can't see or retrieve any controls in VLC (play/pause/subtitles/...) after I right click the mouse to switch to VLC from the default player which freezes very often while playing streams.. 

any ideas here?

**Comment by shivasiddharth** [comment]
Issues with VLC Have been fixed in the last update. It supports controls and subtitles. Forgot to update here.
