### ISSUE TITLE
Error on playback

### ISSUE THREAD

**Issue by enydrueda** [shivasiddharth/Stremio-RaspberryPi#12]
Stremio show me "Playback error, please try again" during the load of a movie

**Comment by lowflier** [comment]
Same for me. Installed Stremio on Raspberry Pi 4 yesterday (clean install with PureFTP on PPP). Couldn't get it to play content from any source.

**Comment by shivasiddharth** [comment]
Check the number of seeds guys. Move your mouse over the Globe icon and check for the speed.

**Comment by shivasiddharth** [comment]
This was fixed long time back. Closing this issue.
