### ISSUE TITLE
123movies can't play 1080p, but 720p works fine

### ISSUE THREAD

**Issue by Dyras** [shivasiddharth/Stremio-RaspberryPi#20]
Hello! I've noticed that for whatever reason 123movies can't play 1080p content, for seemingly any movie.

720p on the other hand works almost instantly, ever time.

Anyone else with a similar problem?

Raspberry Pi 4, latest Raspberry Pi OS.

It gets stuck like this, and it never ever plays:
![grafik](https://user-images.githubusercontent.com/12563436/123798110-297c7780-d8e7-11eb-8cde-766a9dec02b0.png)

**Comment by shivasiddharth** [comment]
Check the number of SEEDS. I have no control of what plays what. Using the ```sudo raspi-config``` increase the GPU memory if you have Pi4.  Install H264ify plugin in chromium. Last suggestion is to use VLC.

**Comment by shivasiddharth** [comment]
You can remote access Stremio server on Apple devices/Windows/Android. Open a browser and type in https://IP-ADDRESS-OF-PI:12470 This will openup stremio on other devices. You need not install apps individually in all your devices. For ref: https://www.youtube.com/watch?v=cYmpVh_GWJg

**Comment by Dyras** [comment]
Haven't noticed any issues with the seeds. The exact same videos work on Windows.

Will try to increase the GPU memory though. Feeling dead this weekend so I'll test about on Monday or so.

**Comment by shivasiddharth** [comment]
Fixed !
