### ISSUE TITLE
What's the easiest way of updating?

### ISSUE THREAD

**Issue by Dyras** [shivasiddharth/Stremio-RaspberryPi#24]
Hello! I find the install guide to be great, but it makes no mention of the best way to update Stremio.

Any chance that could be added?

**Comment by shivasiddharth** [comment]
IF you already have the services setup, the easiest way to update would be to delete the existing folder and re-clone the git.

**Comment by Dyras** [comment]
That's what I did last time, I was just curious if there was an easier/official way :)

**Comment by shivasiddharth** [comment]
Thats the easiest way to update the project. Re-cloning the project is just a one line command. Things can't get easier than this.

**Comment by Dyras** [comment]
Indeed!
