### ISSUE TITLE
Can't find the debs

### ISSUE THREAD

**Issue by vliapis** [shivasiddharth/Stremio-RaspberryPi#38]
Hello
edit: sorry delete

> Try if you can capture the error next time. Previously the stremio was running on a browser and making Pi slow. These binaries are much better than the previous methods.

i've used the stremio with the server exe/browser seperate "installation". It wasn't the best experience, but it worked with a few nicks here and there which usualy worked out by killing procs and re-launching them. My last working installation was with the two .debs and it suddenly stopped working (as semi-explained before). Don't know if i somehow broke my OS (i did a change by adding a new DE on my rpi64OS, from LXDE to Mate and found it that it might make my video display lose more FPS (might not even be the culprit, i guess that even at 2.2Ghz, when the stremio happen to load a video thats .mkv, no matter the resolution, the pi4 struggles, which is sad). 

If I get the same error along the way i'll be sure to bring it to your attention. 

Thank you again and goodmorning from Greece.

**Comment by shivasiddharth** [comment]
I don't understand ! What's the issue ?

**Comment by vliapis** [comment]
hi, while it doesnt display on my rpi crhomium, i found it on my x86 machine as per usual, dont know why. Good morning and thank you!

I had an issue where the stremio would exit with a opengl state > 0 or something as soon as the video was buffered and was about to display it (might be able to find the error and post it) and i end up rolling back to a fresh OS (reset the OS) on rpi.

**Comment by shivasiddharth** [comment]
Try if you can capture the error next time. Previously the stremio was running on a browser and making Pi slow. These binaries are much better than the previous methods.
