### ISSUE TITLE
Failing installation 

### ISSUE THREAD

**Issue by techiesanta** [shivasiddharth/Stremio-RaspberryPi#40]
Hi There, 

Followed your installation notes from binary a couple of times - in case i missed a section however I still can't seem to install Stremio onto my raspberry pi 4. 

Have downloaded and extracted both Stremio 32bit armhf and source code to my home folder. 

Running the Debian bullseye script seems to come up with error regarding no public key. 
Then running the install is state some packages could not be installed  and that packages have unmet dependencies. 

Is there a way to correct these? 

Thank you in advance.

**Comment by shivasiddharth** [comment]
Please check the Notes https://github.com/shivasiddharth/Stremio-RaspberryPi#note I have covered every possible error scenario.
