### ISSUE TITLE
Tutorial uses arm64 architecture, but Stremio download is amd64

### ISSUE THREAD

**Issue by PedroRodr** [shivasiddharth/Stremio-RaspberryPi#41]
Hello! I've tried to follow your tutorial, but you use the arm64 version of it. In the Stremio website I can only download the amd64 version of it. How do I make this change to work?
I'm attaching a screenshot showing where the issue is present.

Thank you in advance

![Untitled](https://user-images.githubusercontent.com/6168680/177601185-476ae470-7698-466b-b5a5-6e927f9a3f51.png)

**Comment by shivasiddharth** [comment]
amd64 is for x86 architecture based Intel/AMD computers. Its not applicable for Pi which is arm based. I don't understand as to why you are mixing two different things.
