### ISSUE TITLE
Streamio could not update casting device

### ISSUE THREAD

**Issue by HalinSky** [shivasiddharth/Stremio-RaspberryPi#7]
I have a Streamio running on Raspberry Pi 2 with recommended Noobs Rasbian distro.

I cannot run any movie, I installed some addons (Torrentio, TPB, YTS, Anime Kitsu, Subtitles etc.)
I think it wants to cast to my tv instead of just displaying on the screen?

**Comment by shivasiddharth** [comment]
Do you have vlc installed ?

**Comment by HalinSky** [comment]
I have restarted my Raspberry Pi and issue dissapeared. I still am not aware why it occured though.
